# kcenon-monitoring-system portfile
# High-performance C++20 monitoring system with metrics, tracing, and alerting

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO kcenon/monitoring_system
    REF "v${VERSION}"
    SHA512 65e6e23cfa8ae49b653230d13ff111c393eda35bcd45802e0b8318028fc36aeed9bf92300d5c7a8b41618e0da7689852930ad3d2ea0a82011ef45973de1d03e4
    HEAD_REF main
)

# Feature-based options
set(MONITORING_WITH_LOGGER OFF)
if("logging" IN_LIST FEATURES)
    set(MONITORING_WITH_LOGGER ON)
endif()

set(MONITORING_WITH_NETWORK OFF)
if("network" IN_LIST FEATURES)
    set(MONITORING_WITH_NETWORK ON)
endif()

set(MONITORING_WITH_GRPC_TRANSPORT OFF)
if("grpc" IN_LIST FEATURES)
    set(MONITORING_WITH_GRPC_TRANSPORT ON)
endif()

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DMONITORING_BUILD_TESTS=OFF
        -DMONITORING_BUILD_INTEGRATION_TESTS=OFF
        -DMONITORING_BUILD_EXAMPLES=OFF
        -DMONITORING_BUILD_BENCHMARKS=OFF
        -DMONITORING_WITH_COMMON_SYSTEM=ON
        -DMONITORING_WITH_THREAD_SYSTEM=ON
        -DMONITORING_WITH_LOGGER_SYSTEM=${MONITORING_WITH_LOGGER}
        -DMONITORING_WITH_NETWORK_SYSTEM=${MONITORING_WITH_NETWORK}
        -DMONITORING_WITH_GRPC=${MONITORING_WITH_GRPC_TRANSPORT}
        -DFETCHCONTENT_FULLY_DISCONNECTED=ON
)

vcpkg_cmake_install()

vcpkg_cmake_config_fixup(
    PACKAGE_NAME monitoring_system
    CONFIG_PATH lib/cmake/monitoring_system
)

# Create a shim that defines aliases for build-tree targets referenced in
# monitoring_system-targets.cmake (thread_system::thread_system, kcenon::common_system)
# before the targets file is loaded.
file(WRITE "${CURRENT_PACKAGES_DIR}/share/monitoring_system/monitoring_system-target-aliases.cmake" [=[
# Auto-generated by vcpkg portfile — create INTERFACE IMPORTED aliases
# for build-tree-only targets referenced in monitoring_system-targets.cmake
if(TARGET thread_system::thread_base AND NOT TARGET thread_system::thread_system)
    add_library(thread_system::thread_system INTERFACE IMPORTED)
    set_target_properties(thread_system::thread_system PROPERTIES
        INTERFACE_LINK_LIBRARIES "thread_system::thread_base")
endif()
if(TARGET common_system::common_system AND NOT TARGET kcenon::common_system)
    add_library(kcenon::common_system INTERFACE IMPORTED)
    set_target_properties(kcenon::common_system PROPERTIES
        INTERFACE_LINK_LIBRARIES "common_system::common_system")
endif()
]=])

# Inject find_dependency calls and the shim into the config file,
# right before the targets include.  Without the find_dependency calls
# the transitive targets (thread_system, common_system) do not exist
# when the shim runs, so the aliases are never created.
vcpkg_replace_string(
    "${CURRENT_PACKAGES_DIR}/share/monitoring_system/monitoring_system-config.cmake"
    [[if(EXISTS "${CMAKE_CURRENT_LIST_DIR}/monitoring_system-targets.cmake")
    include("${CMAKE_CURRENT_LIST_DIR}/monitoring_system-targets.cmake")
endif()]]
    [[include(CMakeFindDependencyMacro)
find_dependency(common_system CONFIG)
find_dependency(thread_system CONFIG)
include("${CMAKE_CURRENT_LIST_DIR}/monitoring_system-target-aliases.cmake")
if(EXISTS "${CMAKE_CURRENT_LIST_DIR}/monitoring_system-targets.cmake")
    include("${CMAKE_CURRENT_LIST_DIR}/monitoring_system-targets.cmake")
endif()]]
)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")
